// Word 文档生成服务（docx 库）

import { saveFile } from "./storage";

export async function generateWord(title: string, content: string, lang: string): Promise<Buffer> {
  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
  } = await import("docx");

  const paragraphs: any[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: `Language: ${lang.toUpperCase()} | Generated by SeaReport Translator`, italics: true, size: 20 })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({ text: "" }),
  ];

  // 简单按段落拆分
  const blocks = content.split(/\n{2,}/);
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    if (/^#\s/.test(trimmed)) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.replace(/^#\s/, ""),
          heading: HeadingLevel.HEADING_2,
        })
      );
    } else {
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed, size: 22 })],
        })
      );
    }
    paragraphs.push(new Paragraph({ text: "" }));
  }

  const doc = new Document({
    sections: [{ properties: {}, children: paragraphs }],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

export async function saveWord(buffer: Buffer, fileName: string): Promise<string> {
  const { url } = await saveFile(`outputs/${fileName}`, buffer, {
    contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });
  return url;
}
